Use cmake -S and -B parameters in github action
lefticus/cpp_starter_project pull request #132
Opened 2021-03-24 19:18 UTC by wirew0rm

When reviewing the github action for a project based on the template I noticed that all github platforms now provice cmake > 3.12, so we can replace the comment advocating -S and -B and just use it \o/. I only later noticed that the template only builds on linux, thats why I also included the versions for the other platforms for which we build.

Cmake versions at this time on the different platforms:
CMake 3.19.7 (ubuntu-latest [1])
Cmake 3.19.6 (macos-latest [2])
CMake 3.19.7 (windows-latest [3])

[1] https://github.com/actions/virtual-environments/blob/ubuntu20/20210318.0/images/linux/Ubuntu2004-README.md#tools
[2] https://github.com/actions/virtual-environments/blob/macOS-10.15/20210314.1/images/macos/macos-10.15-Readme.md#tools
[3] https://github.com/actions/virtual-environments/blob/win19/20210316.1/images/win/Windows2019-Readme.md#tools

2021-08-02 22:57 UTC, aminya commented
This is already included in #91

2021-08-02 23:06 UTC, aminya requested changes
This is already included in #91

2021-08-05 06:43 UTC, wirew0rm commented
closed in favor of #91, thanks for cleaning up the PRs here @aminya :+1:

2021-08-05 06:43 UTC, closed without merging

2021-08-05 07:03 UTC, aminya commented
Thanks. You're welcome!